// GENERATED by scripts/gen-widgets.mjs — do not edit by hand.
// Source: the build's gradle.properties. Re-run `node scripts/gen-widgets.mjs` to refresh.

export const META = {
  "version": "0.1.0",
  "elementaVersion": "745",
  "universalcraftVersion": "505",
  "owner": "Brassworks-smp",
  "repo": "BrassUi",
  "repoUrl": "https://github.com/Brassworks-smp/BrassUi",
  "packagesUrl": "https://maven.pkg.github.com/Brassworks-smp/BrassUi"
} as const;
