// GENERATED by scripts/gen-widgets.mjs - do not edit by hand.
// Source: brassui core Kotlin sources. Re-run `node scripts/gen-widgets.mjs` to refresh.

export type Param = {
  name: string;
  type: string;
  default?: string;
  doc?: string;
};

export type Widget = {
  name: string;
  kind: "class" | "object" | "interface";
  category: string;
  categoryDir: string;
  slug: string;
  summary: string;
  params: Param[];
  examples: string[];
  signature: string;
  demoName?: string;
};

export const CATEGORIES = [
  {
    "dir": "input",
    "label": "Inputs",
    "blurb": "Buttons, toggles, sliders, fields. The controls a player drives."
  },
  {
    "dir": "layout",
    "label": "Layout",
    "blurb": "Panels, scroll areas, flow, spacing. How a screen is arranged."
  },
  {
    "dir": "surface",
    "label": "Surfaces",
    "blurb": "Cards, dialogs, tables, charts. The framed regions content sits in."
  },
  {
    "dir": "text",
    "label": "Text",
    "blurb": "Labels, markdown, tags, code. Everything typographic."
  },
  {
    "dir": "media",
    "label": "Media",
    "blurb": "Images, icons, player heads, item and entity previews."
  }
] as const;

export const WIDGETS: Widget[] = [
  {
    "name": "BrassButton",
    "kind": "class",
    "category": "Inputs",
    "categoryDir": "input",
    "slug": "BrassButton",
    "summary": "A keycap BrassWidget with a centred label that inherits all the base animation (hover, lift, animated colours, entrance).",
    "params": [
      {
        "name": "label",
        "type": "String"
      },
      {
        "name": "accent",
        "type": "BrassAccent",
        "default": "BrassAccent.DEFAULT"
      },
      {
        "name": "onClick",
        "type": "() -> Unit",
        "default": "{}"
      }
    ],
    "examples": [
      "BrassButton(\"Primary action\", BrassAccent.BRASS)"
    ],
    "signature": "class BrassButton(\n    var label: String,\n    accent: BrassAccent = BrassAccent.DEFAULT,\n    private val onClick: (), > Unit = {},\n) : BrassWidget(accent), BrassFocusable",
    "demoName": "button"
  },
  {
    "name": "BrassCheckbox",
    "kind": "class",
    "category": "Inputs",
    "categoryDir": "input",
    "slug": "BrassCheckbox",
    "summary": "A checkbox, a small keycap that goes brass and shows a pixel check glyph when ticked.",
    "params": [
      {
        "name": "initial",
        "type": "Boolean",
        "default": "false"
      },
      {
        "name": "icon",
        "type": "BrassIcons.Icon",
        "default": "BrassIcons.CHECK",
        "doc": "Glyph drawn in the box."
      },
      {
        "name": "onChange",
        "type": "(Boolean) -> Unit",
        "default": "{}"
      }
    ],
    "examples": [
      "BrassCheckbox(initial = false)"
    ],
    "signature": "class BrassCheckbox(\n    initial: Boolean = false,\n    private val fixedAccent: BrassAccent? = null,\n    icon: BrassIcons.Icon = BrassIcons.CHECK,\n    private val alwaysShowIcon: Boolean = false,\n    private val onChange: (Boolean), > Unit = {},\n) : BrassWidget(fixedAccent ?: if (initial) BrassAccent.BRASS else BrassAccent.DEFAULT),\n    BrassValue<Boolean>, BrassFocusable",
    "demoName": "checkbox"
  },
  {
    "name": "BrassChips",
    "kind": "class",
    "category": "Inputs",
    "categoryDir": "input",
    "slug": "BrassChips",
    "summary": "A multi, select shown as removable chips, selected filters, applied tags, chosen recipients.",
    "params": [
      {
        "name": "maxChipWidth",
        "type": "Float",
        "default": "120f",
        "doc": "How wide a chip may get before its label is clipped."
      },
      {
        "name": "onRemove",
        "type": "((String) -> Unit)?",
        "default": "null",
        "doc": "Called when a chip's X is clicked."
      },
      {
        "name": "onClick",
        "type": "((String) -> Unit)?",
        "default": "null",
        "doc": "Called when a chip's body is clicked."
      }
    ],
    "examples": [
      "val chips = BrassChips(onRemove = { filters.remove(it) })\nchips.set(listOf(\"survival\", \"hardcore\", \"1.21\"))",
      "val chips = BrassChips()\nval items = mutableListOf(\n    Chip(\"survival\", BrassTagStyle.SUCCESS),\n    Chip(\"hardcore\", BrassTagStyle.ERROR),\n    Chip(\"modded\", BrassTagStyle.INFO),\n)\nchips.set(items)\nchips.onRemove = { label ->\n    items.removeAll { it.label == label }\n    chips.set(items)\n}\nchips"
    ],
    "signature": "class BrassChips(\n    var maxChipWidth: Float = 120f,\n    var onRemove: ((String), > Unit)? = null,\n    var onClick: ((String), > Unit)? = null,\n) : BrassWidget(BrassAccent.DEFAULT)",
    "demoName": "chips"
  },
  {
    "name": "BrassColorPicker",
    "kind": "class",
    "category": "Inputs",
    "categoryDir": "input",
    "slug": "BrassColorPicker",
    "summary": "A colour picker, laid out as a single **card**: a saturation/value square with a live preview swatch beside it, a hue strip below, and an editable **hex field** along the bottom.",
    "params": [
      {
        "name": "initial",
        "type": "Color",
        "default": "Colors.BRASS_500"
      },
      {
        "name": "onPick",
        "type": "(Color) -> Unit",
        "default": "{}"
      }
    ],
    "examples": [
      "BrassColorPicker(Colors.BRASS_500)"
    ],
    "signature": "class BrassColorPicker(\n    initial: Color = Colors.BRASS_500,\n    private val onPick: (Color), > Unit = {},\n) : BrassWidget(BrassAccent.DEFAULT), BrassValue<Color>",
    "demoName": "color-picker"
  },
  {
    "name": "BrassConfirmSlider",
    "kind": "class",
    "category": "Inputs",
    "categoryDir": "input",
    "slug": "BrassConfirmSlider",
    "summary": "Hold it down to confirm, for the one action you cannot take back.",
    "params": [
      {
        "name": "label",
        "type": "String",
        "default": "\"Hold to confirm\"",
        "doc": "The prompt shown on the button while it is armed."
      },
      {
        "name": "confirmedLabel",
        "type": "String",
        "default": "\"Confirmed\"",
        "doc": "Shown once the hold completes."
      },
      {
        "name": "accent",
        "type": "BrassAccent",
        "default": "BrassAccent.DANGER",
        "doc": "The button's accent."
      },
      {
        "name": "onConfirm",
        "type": "() -> Unit",
        "default": "{}"
      }
    ],
    "examples": [
      "BrassConfirmSlider(\"Hold to sell 40,000\") { market.sell(order) }",
      "BrassConfirmSlider(\"Hold to delete world\")"
    ],
    "signature": "class BrassConfirmSlider(\n    var label: String = \"Hold to confirm\",\n    var confirmedLabel: String = \"Confirmed\",\n    accent: BrassAccent = BrassAccent.DANGER,\n    var holdSeconds: Float = DEFAULT_HOLD,\n    private val onConfirm: (), > Unit = {},\n) : BrassWidget(accent), BrassFocusable",
    "demoName": "confirm-slider"
  },
  {
    "name": "BrassDropdown",
    "kind": "class",
    "category": "Inputs",
    "categoryDir": "input",
    "slug": "BrassDropdown",
    "summary": "An in, place accordion dropdown: a keycap field showing the current label and a chevron that flips when open, and a menu of keycap option rows that expands below (pushing following content down) so…",
    "params": [
      {
        "name": "options",
        "type": "List<Pair<String, String>>"
      },
      {
        "name": "initial",
        "type": "String",
        "default": "options.firstOrNull()?.first ?: \"\""
      },
      {
        "name": "onSelect",
        "type": "(String) -> Unit",
        "default": "{}"
      }
    ],
    "examples": [
      "BrassDropdown(\n    listOf(\"low\" to \"Low detail\", \"med\" to \"Medium detail\", \"high\" to \"High detail\"),\n)"
    ],
    "signature": "class BrassDropdown(\n    private val options: List<Pair<String, String>>,\n    initial: String = options.firstOrNull()?.first ?: \"\",\n    private val onSelect: (String), > Unit = {},\n) : UIContainer(), BrassValue<String>",
    "demoName": "dropdown"
  },
  {
    "name": "BrassIconButton",
    "kind": "class",
    "category": "Inputs",
    "categoryDir": "input",
    "slug": "BrassIconButton",
    "summary": "A keycap with a leading pixel icon and a label beside it.",
    "params": [
      {
        "name": "label",
        "type": "String"
      },
      {
        "name": "icon",
        "type": "BrassIcons.Icon"
      },
      {
        "name": "accent",
        "type": "BrassAccent",
        "default": "BrassAccent.DEFAULT"
      },
      {
        "name": "onClick",
        "type": "() -> Unit",
        "default": "{}"
      }
    ],
    "examples": [
      "BrassIconButton(\"Settings\", BrassIcons.GEAR)"
    ],
    "signature": "class BrassIconButton(\n    var label: String,\n    var icon: BrassIcons.Icon,\n    accent: BrassAccent = BrassAccent.DEFAULT,\n    private val onClick: (), > Unit = {},\n) : BrassWidget(accent), BrassFocusable",
    "demoName": "icon-button"
  },
  {
    "name": "BrassInventoryGrid",
    "kind": "class",
    "category": "Inputs",
    "categoryDir": "input",
    "slug": "BrassInventoryGrid",
    "summary": "The soft pastel tint highlight slots wear, the accent heavily lightened.",
    "params": [
      {
        "name": "columns",
        "type": "Int",
        "default": "9",
        "doc": "Slots per row."
      },
      {
        "name": "rows",
        "type": "Int",
        "default": "3",
        "doc": "Number of rows."
      },
      {
        "name": "gap",
        "type": "Float",
        "default": "1f",
        "doc": "Gap between slots."
      }
    ],
    "examples": [
      "val chest = BrassInventoryGrid(columns = 9, rows = 3)\nchest.setSlot(0, BrassInventoryGrid.Slot(\"minecraft:diamond\", 12))\nchest.setSlot(1, BrassInventoryGrid.Slot(\"minecraft:iron_ingot\", 64))\n\nval hotbar = BrassInventoryGrid(columns = 9, rows = 1)\nhotbar.linkTo(chest)   // one cursor between them; shift-click and drags cross"
    ],
    "signature": "class BrassInventoryGrid(\n    var columns: Int = 9,\n    var rows: Int = 3,\n    var slotSize: Float = 18f,\n    var gap: Float = 1f,\n) : BrassWidget(BrassAccent.DEFAULT)",
    "demoName": "inventory-grid"
  },
  {
    "name": "BrassInventoryLink",
    "kind": "class",
    "category": "Inputs",
    "categoryDir": "input",
    "slug": "BrassInventoryLink",
    "summary": "What a group of BrassInventoryGrids share: the stack on the cursor, and any drag in progress.",
    "params": [],
    "examples": [
      "val chest = BrassInventoryGrid(columns = 9, rows = 3)\nval hotbar = BrassInventoryGrid(columns = 9, rows = 1)\nhotbar.linkTo(chest)   // now shift-click and cross-grid drags work between them"
    ],
    "signature": "class BrassInventoryLink"
  },
  {
    "name": "BrassKeybind",
    "kind": "class",
    "category": "Inputs",
    "categoryDir": "input",
    "slug": "BrassKeybind",
    "summary": "Click to capture a key or mouse chord, the control every settings screen needs and the toolkit had none of.",
    "params": [
      {
        "name": "initial",
        "type": "BrassKeyChord",
        "default": "BrassKeyChord.NONE"
      },
      {
        "name": "onChange",
        "type": "(BrassKeyChord) -> Unit",
        "default": "{}"
      }
    ],
    "examples": [
      "val bind = BrassKeybind(BrassKeyChord(GLFW.GLFW_KEY_G))\nbind.conflictsWith = { chord -> otherBinds.any { it.value == chord } }",
      "BrassKeybind(BrassKeyChord.NONE)"
    ],
    "signature": "class BrassKeybind(\n    initial: BrassKeyChord = BrassKeyChord.NONE,\n    private val onChange: (BrassKeyChord), > Unit = {},\n) : BrassWidget(BrassAccent.DEFAULT), BrassValue<BrassKeyChord>, BrassFocusable",
    "demoName": "keybind"
  },
  {
    "name": "BrassKeyChord",
    "kind": "class",
    "category": "Inputs",
    "categoryDir": "input",
    "slug": "BrassKeyChord",
    "summary": "A key or mouse binding: one main input plus whichever modifiers were held with it.",
    "params": [
      {
        "name": "ctrl",
        "type": "Boolean",
        "default": "false"
      },
      {
        "name": "shift",
        "type": "Boolean",
        "default": "false"
      },
      {
        "name": "alt",
        "type": "Boolean",
        "default": "false"
      }
    ],
    "examples": [],
    "signature": "class BrassKeyChord(\n    val code: Int = GLFW.GLFW_KEY_UNKNOWN,\n    val ctrl: Boolean = false,\n    val shift: Boolean = false,\n    val alt: Boolean = false,\n)"
  },
  {
    "name": "BrassNumberInput",
    "kind": "class",
    "category": "Inputs",
    "categoryDir": "input",
    "slug": "BrassNumberInput",
    "summary": "An exact number: a value with a step button at each end, and a middle you can drag to scrub.",
    "params": [
      {
        "name": "range",
        "type": "BrassRange",
        "default": "BrassRange(0f, 100f, step = 1f)",
        "doc": "Bounds and quantisation."
      },
      {
        "name": "initial",
        "type": "Float",
        "default": "0f"
      },
      {
        "name": "onChange",
        "type": "(Float) -> Unit",
        "default": "{}"
      }
    ],
    "examples": [
      "BrassNumberInput(BrassRange(0f, 64f, step = 1f), initial = 16f) { count = it.toInt() }",
      "BrassNumberInput(BrassRange(0f, 100f, step = 1f), initial = 42f, suffix = \"%\")"
    ],
    "signature": "class BrassNumberInput(\n    val range: BrassRange = BrassRange(0f, 100f, step = 1f),\n    initial: Float = 0f,\n    var suffix: String = \"\",\n    private val onChange: (Float), > Unit = {},\n) : BrassWidget(BrassAccent.DEFAULT), BrassValue<Float>, BrassFocusable",
    "demoName": "number-input"
  },
  {
    "name": "BrassRadioGroup",
    "kind": "class",
    "category": "Inputs",
    "categoryDir": "input",
    "slug": "BrassRadioGroup",
    "summary": "Exactly one of a set of BrassCheckboxes ticked at a time.",
    "params": [
      {
        "name": "initial",
        "type": "T?",
        "default": "null"
      },
      {
        "name": "onChange",
        "type": "(T?) -> Unit",
        "default": "{}"
      }
    ],
    "examples": [
      "val mode = BrassRadioGroup<String>()\nmode.register(\"fast\", fastBox)\nmode.register(\"safe\", safeBox)\nmode.value = \"safe\""
    ],
    "signature": "class BrassRadioGroup<T>(\n    initial: T? = null,\n    private val onChange: (T?), > Unit = {},\n) : BrassValue<T?>",
    "demoName": "radio-group"
  },
  {
    "name": "BrassRange",
    "kind": "class",
    "category": "Inputs",
    "categoryDir": "input",
    "slug": "BrassRange",
    "summary": "A bounded numeric range with an optional step, what BrassSlider, BrassNumberInput and BrassRangeSlider all mean by \"a value between min and max\".",
    "params": [
      {
        "name": "min",
        "type": "Float",
        "default": "0f"
      },
      {
        "name": "max",
        "type": "Float",
        "default": "1f"
      },
      {
        "name": "step",
        "type": "Float",
        "default": "0f",
        "doc": "Quantisation."
      }
    ],
    "examples": [],
    "signature": "class BrassRange(\n    val min: Float = 0f,\n    val max: Float = 1f,\n    val step: Float = 0f,\n)"
  },
  {
    "name": "BrassRangeSlider",
    "kind": "class",
    "category": "Inputs",
    "categoryDir": "input",
    "slug": "BrassRangeSlider",
    "summary": "A slider with two handles, a filter's \"between 20 and 60\", a price band, a level range.",
    "params": [
      {
        "name": "range",
        "type": "BrassRange",
        "default": "BrassRange(0f, 1f)"
      },
      {
        "name": "low",
        "type": "Float",
        "default": "0f"
      },
      {
        "name": "high",
        "type": "Float",
        "default": "1f"
      },
      {
        "name": "suffix",
        "type": "String",
        "default": "\"\"",
        "doc": "Text after each number in the readout."
      },
      {
        "name": "onChange",
        "type": "(low: Float, high: Float) -> Unit",
        "default": "{ _, _ -> }"
      }
    ],
    "examples": [
      "BrassRangeSlider(BrassRange(0f, 100f, step = 1f), low = 20f, high = 60f) { lo, hi -> filter(lo, hi) }",
      "BrassRangeSlider(BrassRange(0f, 100f), low = 15f, high = 85f, suffix = \"%\")"
    ],
    "signature": "class BrassRangeSlider(\n    val range: BrassRange = BrassRange(0f, 1f),\n    low: Float = 0f,\n    high: Float = 1f,\n    var suffix: String = \"\",\n    private val onChange: (low: Float, high: Float), > Unit = { _, _, > },\n) : BrassWidget(BrassAccent.DEFAULT), BrassFocusable",
    "demoName": "range-slider"
  },
  {
    "name": "BrassScrollSelector",
    "kind": "class",
    "category": "Inputs",
    "categoryDir": "input",
    "slug": "BrassScrollSelector",
    "summary": "A horizontal option carousel.",
    "params": [
      {
        "name": "options",
        "type": "List<String>"
      },
      {
        "name": "initialIndex",
        "type": "Int",
        "default": "0"
      },
      {
        "name": "onChange",
        "type": "(Int) -> Unit",
        "default": "{}"
      }
    ],
    "examples": [
      "BrassScrollSelector(listOf(\"Low\", \"Medium\", \"High\", \"Ultra\"))"
    ],
    "signature": "class BrassScrollSelector(\n    private val options: List<String>,\n    initialIndex: Int = 0,\n    private val onChange: (Int), > Unit = {},\n) : BrassWidget(BrassAccent.DEFAULT), BrassValue<Int>, BrassFocusable",
    "demoName": "scroll-selector"
  },
  {
    "name": "BrassSearchField",
    "kind": "class",
    "category": "Inputs",
    "categoryDir": "input",
    "slug": "BrassSearchField",
    "summary": "A text field for filtering: a search glyph, a clear button that appears once there is something to clear, and a debounce so the filter runs when typing pauses rather than on every keystroke.",
    "params": [
      {
        "name": "placeholder",
        "type": "String",
        "default": "\"Search…\""
      },
      {
        "name": "onSearch",
        "type": "(String) -> Unit",
        "default": "{}"
      }
    ],
    "examples": [
      "BrassSearchField(\"Filter players…\") { query -> table.setRows(BrassFuzzy.rank(query, all) { it.name }) }",
      "BrassSearchField(\"Search items…\")"
    ],
    "signature": "class BrassSearchField(\n    placeholder: String = \"Search…\",\n    var debounce: Float = 0.2f,\n    private val onSearch: (String), > Unit = {},\n) : BrassWidget(BrassAccent.DEFAULT)",
    "demoName": "search-field"
  },
  {
    "name": "BrassSlider",
    "kind": "class",
    "category": "Inputs",
    "categoryDir": "input",
    "slug": "BrassSlider",
    "summary": "A slider built from the toolkit's **filled, card** shape (see filledTrack), the same recessed card the progress bar uses, filled with brass up to the value.",
    "params": [
      {
        "name": "min",
        "type": "Float"
      },
      {
        "name": "max",
        "type": "Float"
      },
      {
        "name": "initial",
        "type": "Float"
      },
      {
        "name": "step",
        "type": "Float",
        "default": "0f"
      },
      {
        "name": "format",
        "type": "(Float) -> String",
        "default": "{ String.format(\"%.2f\", it) }"
      },
      {
        "name": "onChange",
        "type": "(Float) -> Unit",
        "default": "{}"
      }
    ],
    "examples": [
      "BrassSlider(0f, 100f, 24f, format = { \"${it.toInt()}%\" })"
    ],
    "signature": "class BrassSlider(\n    private val min: Float,\n    private val max: Float,\n    initial: Float,\n    private val step: Float = 0f,\n    private val format: (Float), > String = { String.format(\"%.2f\", it) },\n    private val onChange: (Float), > Unit = {},\n) : BrassWidget(BrassAccent.DEFAULT), BrassValue<Float>, BrassFocusable",
    "demoName": "slider"
  },
  {
    "name": "BrassSquareButton",
    "kind": "class",
    "category": "Inputs",
    "categoryDir": "input",
    "slug": "BrassSquareButton",
    "summary": "A small keycap that shows a single centred pixel icon (a Icon).",
    "params": [
      {
        "name": "icon",
        "type": "BrassIcons.Icon"
      },
      {
        "name": "accent",
        "type": "BrassAccent",
        "default": "BrassAccent.DEFAULT"
      },
      {
        "name": "iconColor",
        "type": "Color?",
        "default": "null"
      },
      {
        "name": "onClick",
        "type": "() -> Unit",
        "default": "{}"
      }
    ],
    "examples": [
      "BrassSquareButton(BrassIcons.CHECK)"
    ],
    "signature": "class BrassSquareButton(\n    var icon: BrassIcons.Icon,\n    accent: BrassAccent = BrassAccent.DEFAULT,\n    private val iconColor: Color? = null,\n    private val onClick: (), > Unit = {},\n) : BrassWidget(accent), BrassFocusable",
    "demoName": "square-button"
  },
  {
    "name": "BrassTabSwitch",
    "kind": "class",
    "category": "Inputs",
    "categoryDir": "input",
    "slug": "BrassTabSwitch",
    "summary": "A segmented row of keycap tabs, exactly one selected.",
    "params": [
      {
        "name": "options",
        "type": "List<String>"
      },
      {
        "name": "initialIndex",
        "type": "Int",
        "default": "0"
      },
      {
        "name": "equalWidths",
        "type": "Boolean",
        "default": "false",
        "doc": "Split the available width evenly instead of sizing each tab to its label."
      },
      {
        "name": "onChange",
        "type": "(Int) -> Unit",
        "default": "{}"
      }
    ],
    "examples": [
      "BrassTabSwitch(listOf(\"Overview\", \"Details\", \"History\"))"
    ],
    "signature": "class BrassTabSwitch(\n    private val options: List<String>,\n    initialIndex: Int = 0,\n    private val equalWidths: Boolean = false,\n    private val widths: List<Float?> = emptyList(),\n    var accent: BrassAccent = BrassAccent.BRASS,\n    private val onChange: (Int), > Unit = {},\n) : UIContainer(), BrassValue<Int>",
    "demoName": "tab-switch"
  },
  {
    "name": "BrassToggle",
    "kind": "class",
    "category": "Inputs",
    "categoryDir": "input",
    "slug": "BrassToggle",
    "summary": "A toggle built from the same **filled, card** shape as the slider and progress bar (see filledTrack): a recessed card that fills with brass as it turns on, with a grey grip knob (grip) sliding from…",
    "params": [
      {
        "name": "initial",
        "type": "Boolean",
        "default": "false"
      },
      {
        "name": "onChange",
        "type": "(Boolean) -> Unit",
        "default": "{}"
      }
    ],
    "examples": [
      "BrassToggle(initial = false)"
    ],
    "signature": "class BrassToggle(\n    initial: Boolean = false,\n    private val onChange: (Boolean), > Unit = {},\n) : BrassWidget(BrassAccent.DEFAULT), BrassValue<Boolean>, BrassFocusable",
    "demoName": "toggle"
  },
  {
    "name": "BrassVirtualSlotList",
    "kind": "class",
    "category": "Inputs",
    "categoryDir": "input",
    "slug": "BrassVirtualSlotList",
    "summary": "A virtualized, scrollable one, column list of item slots, a catalogue or search, result list where the rows are **real** BrassInventoryGrid slots.",
    "params": [
      {
        "name": "slotSize",
        "type": "Float",
        "default": "18f"
      },
      {
        "name": "gap",
        "type": "Float",
        "default": "2f"
      },
      {
        "name": "showNames",
        "type": "Boolean",
        "default": "true",
        "doc": "Whether each row draws the item's display name next to its slot."
      }
    ],
    "examples": [],
    "signature": "class BrassVirtualSlotList(\n    slotSize: Float = 18f,\n    gap: Float = 2f,\n    var showNames: Boolean = true,\n) : BrassInventoryGrid(columns = 1, rows = 1, slotSize = slotSize, gap = gap)"
  },
  {
    "name": "BrassBounds",
    "kind": "object",
    "category": "Layout",
    "categoryDir": "layout",
    "slug": "BrassBounds",
    "summary": "Frame geometry that survives the game window being resized.",
    "params": [],
    "examples": [],
    "signature": "object BrassBounds"
  },
  {
    "name": "BrassBreakpoint",
    "kind": "object",
    "category": "Layout",
    "categoryDir": "layout",
    "slug": "BrassBreakpoint",
    "summary": "Size bands, for a layout that has to work at every GUI scale.",
    "params": [],
    "examples": [],
    "signature": "object BrassBreakpoint"
  },
  {
    "name": "BrassCull",
    "kind": "object",
    "category": "Layout",
    "categoryDir": "layout",
    "slug": "BrassCull",
    "summary": "Visibility culling for content a component paints **itself**.",
    "params": [],
    "examples": [],
    "signature": "object BrassCull"
  },
  {
    "name": "BrassDivider",
    "kind": "class",
    "category": "Layout",
    "categoryDir": "layout",
    "slug": "BrassDivider",
    "summary": "A separator rule in the toolkit's grammar: a 1, px recessed groove with a 1, px highlight beside it, the same two, tone bevel the sliders and scrollbar use, running at full strength from end to end…",
    "params": [],
    "examples": [
      "BrassDivider.between(window.content, nav, mainScroll)               // centred in the gap, rail-height\nBrassDivider.between(window.content, nav, main, span = window.content, inset = 0f)  // full-height seam\nBrassDivider.under(panel, heading)                                  // horizontal, across the panel",
      "BrassDivider()"
    ],
    "signature": "class BrassDivider : UIComponent()",
    "demoName": "divider"
  },
  {
    "name": "BrassFlow",
    "kind": "class",
    "category": "Layout",
    "categoryDir": "layout",
    "slug": "BrassFlow",
    "summary": "A flexbox, style wrapping row (CSS `flex, wrap: wrap`).",
    "params": [
      {
        "name": "gapX",
        "type": "Float",
        "default": "6f",
        "doc": "Horizontal gap between items on a line."
      },
      {
        "name": "gapY",
        "type": "Float",
        "default": "6f",
        "doc": "Vertical gap between lines."
      },
      {
        "name": "itemHeight",
        "type": "Float",
        "default": "20f",
        "doc": "Height of each item; every item on a line shares it."
      }
    ],
    "examples": [
      "BrassFlow(itemHeight = 18f).apply {\n    for (label in listOf(\"Survival\", \"Creative\", \"Hardcore\", \"Adventure\", \"Peaceful\", \"Spectator\")) {\n        // A rough width from the label length is enough to seed the wrap; the flow re-measures.\n        add(BrassButton(label, BrassAccent.DEFAULT), label.length * 6f + 14f)\n    }\n}"
    ],
    "signature": "class BrassFlow(\n    private val gapX: Float = 6f,\n    private val gapY: Float = 6f,\n    private val itemHeight: Float = 20f,\n    private val stretch: Boolean = false,\n) : UIContainer()",
    "demoName": "flow"
  },
  {
    "name": "BrassForm",
    "kind": "class",
    "category": "Layout",
    "categoryDir": "layout",
    "slug": "BrassForm",
    "summary": "A scrolling stack of labelled rows, built with a small chaining API and readable back by caption.",
    "params": [],
    "examples": [
      "val form = BrassForm()\n    .addTextField(\"Address\", \"localhost\")\n    .addSlider(\"Volume\", 0f, 1f, 0.8f)\n    .addToggleRow(\"Autostart\", false)\n// ...later\nval settings = form.values()\nform.setValues(saved)"
    ],
    "signature": "class BrassForm(\n    private val rowGap: Float = BrassWidget.BLEED_BOTTOM + 6f,\n) : UIContainer()",
    "demoName": "form"
  },
  {
    "name": "BrassGrid",
    "kind": "class",
    "category": "Layout",
    "categoryDir": "layout",
    "slug": "BrassGrid",
    "summary": "A **weighted grid**: children flow left to right into columns whose widths are shares of the container, wrapping to a new row every columns cells.",
    "params": [
      {
        "name": "weights",
        "type": "List<Float>",
        "default": "listOf(1f, 1f)",
        "doc": "Relative width of each column."
      },
      {
        "name": "rowHeight",
        "type": "Float",
        "default": "20f",
        "doc": "Height of every row."
      },
      {
        "name": "gapX",
        "type": "Float",
        "default": "6f",
        "doc": "Gap between columns and between rows."
      },
      {
        "name": "gapY",
        "type": "Float",
        "default": "6f"
      }
    ],
    "examples": [
      "BrassGrid(weights = listOf(2f, 1f, 1f), rowHeight = 20f)\n    .add(nameField, portField, saveButton)\n    .add(pathField, sizeField, browseButton)",
      "BrassGrid(weights = listOf(1f, 1f, 1f), rowHeight = 18f).add(\n    BrassButton(\"One\", BrassAccent.DEFAULT),\n    BrassButton(\"Two\", BrassAccent.DEFAULT),\n    BrassButton(\"Three\", BrassAccent.DEFAULT),\n    BrassButton(\"Four\", BrassAccent.DEFAULT),\n    BrassButton(\"Five\", BrassAccent.DEFAULT),\n    BrassButton(\"Six\", BrassAccent.DEFAULT),\n)"
    ],
    "signature": "class BrassGrid(\n    private val weights: List<Float> = listOf(1f, 1f),\n    private val rowHeight: Float = 20f,\n    private val gapX: Float = 6f,\n    private val gapY: Float = 6f,\n    private val bleed: Boolean = true,\n) : UIContainer()",
    "demoName": "grid"
  },
  {
    "name": "BrassHBox",
    "kind": "class",
    "category": "Layout",
    "categoryDir": "layout",
    "slug": "BrassHBox",
    "summary": "A **horizontal row**: children are appended left to right with an even gap, and the box sizes itself to what it holds.",
    "params": [
      {
        "name": "gap",
        "type": "Float",
        "default": "6f",
        "doc": "Space between consecutive children."
      }
    ],
    "examples": [
      "BrassHBox(gap = 6f).add(\n    BrassButton(\"Cancel\"),\n    BrassButton(\"Save\", BrassAccent.BRASS),\n) childOf footer"
    ],
    "signature": "class BrassHBox(\n    private val gap: Float = 6f,\n    private val bleed: Boolean = true,\n) : UIContainer()"
  },
  {
    "name": "BrassLayout",
    "kind": "object",
    "category": "Layout",
    "categoryDir": "layout",
    "slug": "BrassLayout",
    "summary": "Layout constraints for building reactive, web, like UIs on Elementa.",
    "params": [],
    "examples": [
      "child.constrain {\n    width = basicWidthConstraint { getWidth() - PAD }   // WRONG - recurses forever\n    width = basicWidthConstraint { this@MyWidget.getWidth() - PAD }   // right\n}"
    ],
    "signature": "object BrassLayout"
  },
  {
    "name": "BrassPageWindow",
    "kind": "object",
    "category": "Layout",
    "categoryDir": "layout",
    "slug": "BrassPageWindow",
    "summary": "Which page numbers a pager shows: `1 … 7 8 9 10 11 … 40`.",
    "params": [],
    "examples": [],
    "signature": "object BrassPageWindow"
  },
  {
    "name": "BrassPagination",
    "kind": "class",
    "category": "Layout",
    "categoryDir": "layout",
    "slug": "BrassPagination",
    "summary": "Page numbers with prev and next, the companion to any list whose data lives on a server.",
    "params": [
      {
        "name": "total",
        "type": "Int",
        "default": "1"
      },
      {
        "name": "current",
        "type": "Int",
        "default": "1"
      },
      {
        "name": "around",
        "type": "Int",
        "default": "1",
        "doc": "Pages shown either side of the current one before an ellipsis takes over."
      },
      {
        "name": "onPage",
        "type": "(Int) -> Unit",
        "default": "{}"
      }
    ],
    "examples": [
      "val pager = BrassPagination(total = 40) { page -> market.load(page) }",
      "val pager = BrassPagination(total = 12, current = 1)\npager.card = true\npager"
    ],
    "signature": "class BrassPagination(\n    total: Int = 1,\n    current: Int = 1,\n    var around: Int = 1,\n    private val onPage: (Int), > Unit = {},\n) : BrassWidget(BrassAccent.DEFAULT), BrassFocusable",
    "demoName": "pagination"
  },
  {
    "name": "BrassRect",
    "kind": "class",
    "category": "Layout",
    "categoryDir": "layout",
    "slug": "BrassRect",
    "summary": "An axis, aligned rectangle.",
    "params": [
      {
        "name": "left",
        "type": "Float",
        "default": "0f"
      },
      {
        "name": "top",
        "type": "Float",
        "default": "0f"
      },
      {
        "name": "right",
        "type": "Float",
        "default": "0f"
      },
      {
        "name": "bottom",
        "type": "Float",
        "default": "0f"
      }
    ],
    "examples": [],
    "signature": "class BrassRect(\n    var left: Float = 0f,\n    var top: Float = 0f,\n    var right: Float = 0f,\n    var bottom: Float = 0f,\n)"
  },
  {
    "name": "BrassResize",
    "kind": "class",
    "category": "Layout",
    "categoryDir": "layout",
    "slug": "BrassResize",
    "summary": "Makes a frame resizable by dragging its edges and corners, as eight invisible grips laid over the border band.",
    "params": [
      {
        "name": "target",
        "type": "UIComponent"
      },
      {
        "name": "minW",
        "type": "Float"
      },
      {
        "name": "minH",
        "type": "Float"
      },
      {
        "name": "onResize",
        "type": "(() -> Unit)?"
      }
    ],
    "examples": [
      "BrassResize.attach(this, minW = 220f, minH = 140f)"
    ],
    "signature": "class BrassResize private constructor(\n    private val target: UIComponent,\n    private val minW: Float,\n    private val minH: Float,\n    private val onResize: ((), > Unit)?,\n)"
  },
  {
    "name": "BrassScrollArea",
    "kind": "class",
    "category": "Layout",
    "categoryDir": "layout",
    "slug": "BrassScrollArea",
    "summary": "A scroll view with its scrollbar and content inset already wired up, the four, line dance every scrolling list otherwise repeats by hand.",
    "params": [
      {
        "name": "scrollbarGap",
        "type": "Float",
        "default": "3f",
        "doc": "Gap between the scrolling body and its scrollbar."
      },
      {
        "name": "alwaysShowBar",
        "type": "Boolean",
        "default": "false",
        "doc": "Keep the scrollbar visible even when the content fits, reserves the gutter so nothing jumps."
      }
    ],
    "examples": [
      "val scroll = ScrollComponent(innerPadding = 0f).constrain {\n    width = 100.percent() - (BrassScrollbar.WIDTH + 3f).pixels()   // reserve the bar's gutter\n    height = 100.percent()\n} childOf host\nBrassScrollbar.attach(host, scroll)                                // or the bar sits on the content\nval column = UIContainer().constrain {\n    x = BrassWidget.BLEED_X.pixels()                               // or inner cards clip on the left\n    width = 100.percent() - (BrassWidget.BLEED_X * 2).pixels()\n    height = BrassLayout.contentHeight()                           // or the list stops short of its end\n} childOf scroll",
      "val list = BrassScrollArea().constrain { … } childOf host\nlist.add(rowA, rowB, rowC)          // vertical stack, or position in `content` by hand"
    ],
    "signature": "class BrassScrollArea @JvmOverloads constructor(\n    private val scrollbarGap: Float = 3f,\n    alwaysShowBar: Boolean = false,\n) : UIContainer()"
  },
  {
    "name": "BrassScrollbar",
    "kind": "class",
    "category": "Layout",
    "categoryDir": "layout",
    "slug": "BrassScrollbar",
    "summary": "A scrollbar in the toolkit's grammar: a thin recessed track with a flat grip that brightens toward brass on hover or while dragged.",
    "params": [],
    "examples": [],
    "signature": "class BrassScrollbar : UIContainer()"
  },
  {
    "name": "BrassScrollbarModel",
    "kind": "class",
    "category": "Layout",
    "categoryDir": "layout",
    "slug": "BrassScrollbarModel",
    "summary": "The arithmetic behind a scrollbar: where the grip sits, how far it travels, and what an offset a drag or a track click implies.",
    "params": [
      {
        "name": "viewport",
        "type": "Float",
        "default": "0f",
        "doc": "Height of the visible area."
      },
      {
        "name": "content",
        "type": "Float",
        "default": "0f",
        "doc": "Total height of the content being scrolled."
      }
    ],
    "examples": [],
    "signature": "class BrassScrollbarModel(\n    var viewport: Float = 0f,\n    var content: Float = 0f,\n    private val minGrip: Float = 12f,\n)"
  },
  {
    "name": "BrassSpacing",
    "kind": "object",
    "category": "Layout",
    "categoryDir": "layout",
    "slug": "BrassSpacing",
    "summary": "The toolkit's spacing scale, the handful of paddings and gaps every card and screen is built from.",
    "params": [],
    "examples": [],
    "signature": "object BrassSpacing"
  },
  {
    "name": "BrassSplitPane",
    "kind": "class",
    "category": "Layout",
    "categoryDir": "layout",
    "slug": "BrassSplitPane",
    "summary": "Two panes with a divider you can drag, a tree beside its details, a list beside a preview, an editor beside its output.",
    "params": [
      {
        "name": "orientation",
        "type": "Orientation",
        "default": "Orientation.HORIZONTAL"
      },
      {
        "name": "first",
        "type": "UIComponent"
      },
      {
        "name": "second",
        "type": "UIComponent"
      }
    ],
    "examples": [
      "// bare\nBrassSplitPane(BrassSplitPane.Orientation.HORIZONTAL, tree, details, split = 0.3f)\n\n// on a card, with the seam running the full inner height\nBrassSplitPane(BrassSplitPane.Orientation.HORIZONTAL, tree, details, card = true)\n    .constrain { width = 100.percent(); height = 160.pixels() }",
      "val pane = BrassSplitPane(\n    first = masterList(),\n    second = detailPane(),\n    split = 0.38f,\n)\npane.card = true\npane"
    ],
    "signature": "class BrassSplitPane(\n    private val orientation: Orientation = Orientation.HORIZONTAL,\n    private val first: UIComponent,\n    private val second: UIComponent,\n    split: Float = 0.5f,\n    var card: Boolean = false,\n    private val minPane: Float = 60f,\n) : BrassWidget(BrassAccent.DEFAULT)",
    "demoName": "split-pane"
  },
  {
    "name": "BrassTreeGuides",
    "kind": "object",
    "category": "Layout",
    "categoryDir": "layout",
    "slug": "BrassTreeGuides",
    "summary": "The anatomy of a tree row: how far it indents, where its expand glyph sits, and the hairlines that connect it to its ancestors.",
    "params": [],
    "examples": [],
    "signature": "object BrassTreeGuides"
  },
  {
    "name": "BrassVBox",
    "kind": "class",
    "category": "Layout",
    "categoryDir": "layout",
    "slug": "BrassVBox",
    "summary": "A **vertical stack**: children are appended top to bottom with an even gap, and the box sizes itself to whatever it ends up holding.",
    "params": [
      {
        "name": "gap",
        "type": "Float",
        "default": "6f",
        "doc": "Space between consecutive children."
      }
    ],
    "examples": [
      "BrassVBox(gap = 8f).add(\n    BrassLabel(\"Server\"),\n    BrassTextInput(),\n    BrassButton(\"Connect\"),\n) childOf card"
    ],
    "signature": "class BrassVBox(\n    private val gap: Float = 6f,\n    private val bleed: Boolean = true,\n) : UIContainer()"
  },
  {
    "name": "BrassVirtualList",
    "kind": "class",
    "category": "Layout",
    "categoryDir": "layout",
    "slug": "BrassVirtualList",
    "summary": "A scrolling list of T that creates **no component per row**, rows are painted directly, and only the handful inside the viewport are touched at all.",
    "params": [
      {
        "name": "rowHeight",
        "type": "Float",
        "default": "16f"
      },
      {
        "name": "onSelect",
        "type": "((T, Int) -> Unit)?",
        "default": "null"
      }
    ],
    "examples": [],
    "signature": "class BrassVirtualList<T>(\n    protected val rowHeight: Float = 16f,\n    private val onSelect: ((T, Int), > Unit)? = null,\n) : BrassWidget(BrassAccent.DEFAULT), BrassFocusable"
  },
  {
    "name": "BrassBlockPreview",
    "kind": "class",
    "category": "Media",
    "categoryDir": "media",
    "slug": "BrassBlockPreview",
    "summary": "A block rendered as an actual 3D model, at the isometric three, quarter angle BrassEntity uses.",
    "params": [
      {
        "name": "blockId",
        "type": "String"
      },
      {
        "name": "followCursor",
        "type": "Boolean",
        "default": "false",
        "doc": "Turn to face the cursor."
      },
      {
        "name": "tooltip",
        "type": "Boolean",
        "default": "true"
      }
    ],
    "examples": [
      "BrassBlockPreview(\"minecraft:blast_furnace\", spin = 30f)\n    .constrain { width = 48.pixels(); height = 48.pixels() }",
      "BrassBlockPreview(\"minecraft:blast_furnace\", spin = 40f)"
    ],
    "signature": "class BrassBlockPreview(\n    var blockId: String,\n    var followCursor: Boolean = false,\n    var spin: Float = 0f,\n    tooltip: Boolean = true,\n) : BrassPlatformVisual(BrassAccent.DEFAULT)",
    "demoName": "block-preview"
  },
  {
    "name": "BrassCanvas",
    "kind": "class",
    "category": "Media",
    "categoryDir": "media",
    "slug": "BrassCanvas",
    "summary": "An escape hatch onto the game's own renderer: a widget, shaped rectangle you can draw *anything* into with `GuiGraphics`.",
    "params": [
      {
        "name": "chrome",
        "type": "BrassChrome",
        "default": "BrassChrome.KEYCAP"
      },
      {
        "name": "clip",
        "type": "Boolean",
        "default": "true",
        "doc": "Clip drawing to the drawing area."
      },
      {
        "name": "accent",
        "type": "BrassAccent",
        "default": "BrassAccent.DEFAULT"
      },
      {
        "name": "content",
        "type": "BrassNativeDraw?",
        "default": "null",
        "doc": "What to paint."
      }
    ],
    "examples": [
      "// on a card, clipped to the card's face\nBrassCanvas { g, w, h -> renderMyThing(g, w, h) }\n    .constrain { width = 64.pixels(); height = 64.pixels() }\n\n// bare rectangle, no chrome at all\nBrassCanvas(chrome = BrassChrome.NONE) { g, w, h -> renderMyThing(g, w, h) }\n    .constrain { width = 100.percent(); height = 120.pixels() }"
    ],
    "signature": "class BrassCanvas(\n    chrome: BrassChrome = BrassChrome.KEYCAP,\n    var inset: Float = 2f,\n    var clip: Boolean = true,\n    var depth: Boolean = true,\n    accent: BrassAccent = BrassAccent.DEFAULT,\n    var content: BrassNativeDraw? = null,\n) : BrassPlatformVisual(accent)"
  },
  {
    "name": "BrassEffectIcon",
    "kind": "class",
    "category": "Media",
    "categoryDir": "media",
    "slug": "BrassEffectIcon",
    "summary": "A status effect: the game's own sprite, with a ring around it counting the remaining duration down.",
    "params": [
      {
        "name": "effectId",
        "type": "String"
      },
      {
        "name": "tooltip",
        "type": "Boolean",
        "default": "true"
      }
    ],
    "examples": [
      "BrassEffectIcon(\"minecraft:speed\", amplifier = 1)\n    .apply { setRemaining(seconds = 42f, of = 180f) }"
    ],
    "signature": "class BrassEffectIcon(\n    var effectId: String,\n    var amplifier: Int = 0,\n    tooltip: Boolean = true,\n) : BrassPlatformVisual(BrassAccent.DEFAULT)",
    "demoName": "effect-icon"
  },
  {
    "name": "BrassEntity",
    "kind": "class",
    "category": "Media",
    "categoryDir": "media",
    "slug": "BrassEntity",
    "summary": "A framed entity preview, the inventory's player model, for any living entity.",
    "params": [
      {
        "name": "entityId",
        "type": "String"
      },
      {
        "name": "followCursor",
        "type": "Boolean",
        "default": "false",
        "doc": "Turn to face the cursor."
      },
      {
        "name": "tooltip",
        "type": "Boolean",
        "default": "true"
      }
    ],
    "examples": [
      "BrassEntity(\"minecraft:allay\", followCursor = true)\n    .constrain { width = 60.pixels(); height = 80.pixels() }",
      "BrassEntity(\"minecraft:allay\", spin = 45f)"
    ],
    "signature": "class BrassEntity(\n    var entityId: String,\n    var followCursor: Boolean = false,\n    var spin: Float = 0f,\n    tooltip: Boolean = true,\n) : BrassPlatformVisual(BrassAccent.DEFAULT)",
    "demoName": "entity"
  },
  {
    "name": "BrassIcons",
    "kind": "object",
    "category": "Media",
    "categoryDir": "media",
    "slug": "BrassIcons",
    "summary": "The toolkit's icon set: a **sprite sheet** at `assets/brassui/textures/gui/icons.png` with an accompanying `icons.json` naming each sprite's rectangle within it.",
    "params": [],
    "examples": [
      "{ \"width\": 96, \"height\": 36, \"cell\": 12,\n  \"sprites\": { \"close\": { \"x\": 0, \"y\": 0, \"w\": 12, \"h\": 12 }, ... } }"
    ],
    "signature": "object BrassIcons"
  },
  {
    "name": "BrassImage",
    "kind": "class",
    "category": "Media",
    "categoryDir": "media",
    "slug": "BrassImage",
    "summary": "An image loaded from a URL, with a **skeleton placeholder** while it is in flight.",
    "params": [
      {
        "name": "url",
        "type": "String"
      },
      {
        "name": "shimmer",
        "type": "Boolean",
        "default": "true",
        "doc": "Draw the skeleton shimmer while loading."
      }
    ],
    "examples": [
      "BrassImage(\"https://example.com/icon.png\")\n    .constrain { width = 24.pixels(); height = 24.pixels() }",
      "BrassImage(SOURCE_URL, shimmer = true, card = true)"
    ],
    "signature": "class BrassImage(\n    url: String,\n    private val shimmer: Boolean = true,\n    private val card: Boolean = false,\n) : BrassWidget(BrassAccent.DEFAULT)",
    "demoName": "image"
  },
  {
    "name": "BrassImageLoader",
    "kind": "object",
    "category": "Media",
    "categoryDir": "media",
    "slug": "BrassImageLoader",
    "summary": "Shared fetch, and, decode for BrassImage: one request per URL for the life of the process, on a small pool of daemon threads.",
    "params": [],
    "examples": [],
    "signature": "object BrassImageLoader"
  },
  {
    "name": "BrassItem",
    "kind": "class",
    "category": "Media",
    "categoryDir": "media",
    "slug": "BrassItem",
    "summary": "An inventory, style slot showing a Minecraft item, the first widget backed by BrassPlatform.",
    "params": [
      {
        "name": "count",
        "type": "Int",
        "default": "1",
        "doc": "Stack size; drawn bottom, right when above 1."
      },
      {
        "name": "tooltip",
        "type": "Boolean",
        "default": "true",
        "doc": "Show the item's name as a tooltip on hover."
      },
      {
        "name": "onClick",
        "type": "(() -> Unit)?",
        "default": "null"
      }
    ],
    "examples": [
      "BrassItem(\"minecraft:diamond_pickaxe\", count = 1)\n    .constrain { width = 18.pixels(); height = 18.pixels() }",
      "BrassItem(\"minecraft:diamond_pickaxe\")"
    ],
    "signature": "class BrassItem(\n    var itemId: String,\n    var count: Int = 1,\n    tooltip: Boolean = true,\n    private val onClick: ((), > Unit)? = null,\n) : BrassPlatformVisual(BrassAccent.DEFAULT)",
    "demoName": "item"
  },
  {
    "name": "BrassPlatformVisual",
    "kind": "class",
    "category": "Media",
    "categoryDir": "media",
    "slug": "BrassPlatformVisual",
    "summary": "The base for every widget whose picture comes from the game rather than from the toolkit, BrassItem, BrassEntity, BrassPlayerHead, BrassBlockPreview, BrassEffectIcon and BrassCanvas.",
    "params": [
      {
        "name": "accent",
        "type": "BrassAccent",
        "default": "BrassAccent.DEFAULT"
      }
    ],
    "examples": [
      "val fade = BrassAmbientFade.earlyOut(entranceFade)\nval hidden = fade <= 0f\nval drawn = hidden || (BrassPlatform.current?.let { runCatching { … }.getOrDefault(false) } ?: false)\nif (!drawn) { … placeholder … }"
    ],
    "signature": "class BrassPlatformVisual(accent: BrassAccent = BrassAccent.DEFAULT) : BrassWidget(accent)"
  },
  {
    "name": "BrassPlayerHead",
    "kind": "class",
    "category": "Media",
    "categoryDir": "media",
    "slug": "BrassPlayerHead",
    "summary": "A player's avatar, the face from their skin, as every player list in the game shows it.",
    "params": [
      {
        "name": "player",
        "type": "String"
      },
      {
        "name": "tooltip",
        "type": "Boolean",
        "default": "true"
      },
      {
        "name": "onClick",
        "type": "(() -> Unit)?",
        "default": "null"
      }
    ],
    "examples": [
      "BrassPlayerHead(\"Notch\")                                    // 18 px card, face from the game skin cache\nBrassPlayerHead(\"Notch\", size = 48f)                        // the same card, bigger\nBrassPlayerHead(uuid, source = BrassPlayerHead.Source.BRASSWORKS)   // face from the BrassWorks API",
      "BrassPlayerHead(DEMO_PLAYER, size = 32f)"
    ],
    "signature": "class BrassPlayerHead(\n    player: String,\n    size: Float = DEFAULT_SIZE,\n    val source: Source = Source.GAME,\n    tooltip: Boolean = true,\n    private val onClick: ((), > Unit)? = null,\n) : BrassPlatformVisual(BrassAccent.DEFAULT)",
    "demoName": "player-head"
  },
  {
    "name": "BrassSkeleton",
    "kind": "class",
    "category": "Media",
    "categoryDir": "media",
    "slug": "BrassSkeleton",
    "summary": "A loading placeholder: a recessed block with a soft highlight sweeping across it.",
    "params": [
      {
        "name": "shimmer",
        "type": "Boolean",
        "default": "true",
        "doc": "Draw the sweeping highlight."
      }
    ],
    "examples": [
      "BrassSkeleton()"
    ],
    "signature": "class BrassSkeleton(\n    var shimmer: Boolean = true,\n) : BrassWidget(BrassAccent.DEFAULT)",
    "demoName": "skeleton"
  },
  {
    "name": "BrassAccordion",
    "kind": "class",
    "category": "Surfaces",
    "categoryDir": "surface",
    "slug": "BrassAccordion",
    "summary": "Collapsible sections, a settings screen's groups, a details panel, anything that is too much at once.",
    "params": [
      {
        "name": "exclusive",
        "type": "Boolean",
        "default": "false",
        "doc": "Whether opening one section closes the others."
      }
    ],
    "examples": [
      "val panel = BrassAccordion()\npanel.section(\"Display\", displayControls, open = true)\npanel.section(\"Advanced\", advancedControls)"
    ],
    "signature": "class BrassAccordion(\n    var exclusive: Boolean = false,\n) : UIContainer()",
    "demoName": "accordion"
  },
  {
    "name": "BrassBarChart",
    "kind": "class",
    "category": "Surfaces",
    "categoryDir": "surface",
    "slug": "BrassBarChart",
    "summary": "Values by category, sales per item, kills per player, votes per map, uptime per shard.",
    "params": [],
    "examples": [
      "val chart = BrassBarChart()\nchart.setBars(listOf(\n    BrassBarChart.Bar(\"Diamond\", 128f),\n    BrassBarChart.Bar(\"Iron\", 96f, Colors.PATINA_400),\n))"
    ],
    "signature": "class BrassBarChart : BrassWidget(BrassAccent.DEFAULT)",
    "demoName": "bar-chart"
  },
  {
    "name": "BrassChart",
    "kind": "class",
    "category": "Surfaces",
    "categoryDir": "surface",
    "slug": "BrassChart",
    "summary": "One or more series plotted over time, TPS, ping, memory, frame time.",
    "params": [
      {
        "name": "window",
        "type": "Int",
        "default": "120",
        "doc": "How many samples are kept per series."
      },
      {
        "name": "fixedMax",
        "type": "Float?",
        "default": "null",
        "doc": "Pin the top of the y axis instead of autoscaling."
      }
    ],
    "examples": [
      "val chart = BrassChart(window = 120)\nval tps = chart.series(\"TPS\", Colors.BRASS_400)\n// each tick:\nchart.push(tps, currentTps)",
      "val chart = BrassChart(window = DEMO_WINDOW, fixedMax = 20f)\nval a = chart.series(\"Requests\", Colors.BRASS_400, filled = true)\nval b = chart.series(\"Errors\", Colors.PATINA_400)\n// Seeded so the plot opens full rather than drawing itself in from an empty axis.\nrepeat(DEMO_WINDOW) { i -> chart.push(a, sample(i)); chart.push(b, noise(i)) }\n\nchart"
    ],
    "signature": "class BrassChart(\n    val window: Int = 120,\n    var fixedMax: Float? = null,\n    var min: Float = 0f,\n) : BrassWidget(BrassAccent.DEFAULT)",
    "demoName": "chart"
  },
  {
    "name": "BrassChat",
    "kind": "class",
    "category": "Surfaces",
    "categoryDir": "surface",
    "slug": "BrassChat",
    "summary": "A chat box: a scrolling message log with a multi, line composer, in the modern messenger idiom — an avatar beside each author's messages, a name, and, time header, and consecutive lines from the sa…",
    "params": [
      {
        "name": "placeholder",
        "type": "String",
        "default": "\"Message…\""
      },
      {
        "name": "onSend",
        "type": "(String) -> Unit",
        "default": "{}",
        "doc": "Called with the trimmed text when the user submits a *new* message."
      }
    ],
    "examples": [
      "val chat = BrassChat(placeholder = \"Message your team…\") { text -> sendToServer(text, chat.replyingTo) }\nchat.constrain { width = 240.pixels(); height = 180.pixels() }\n// ...as messages arrive from anywhere:\nchat.add(\"swzo\", \"prep phase ends in 3 days\", avatar = playerUuid)\nchat.add(\"[server]\", \"The war has begun.\", Colors.DANGER)   // no avatar -> a system line",
      "BrassChat(\"Message the server…\").apply {\n    add(\"Notch\", \"welcome to the server!\", avatar = \"Notch\")\n    add(\"Steve\", \"thanks, how do i claim land?\", avatar = \"Steve\")\n    add(\"Server\", \"Use /claim while standing in a chunk.\")\n}"
    ],
    "signature": "class BrassChat(\n    placeholder: String = \"Message…\",\n    private val onSend: (String), > Unit = {},\n) : BrassWidget(BrassAccent.DEFAULT)",
    "demoName": "chat"
  },
  {
    "name": "BrassCommandPalette",
    "kind": "class",
    "category": "Surfaces",
    "categoryDir": "surface",
    "slug": "BrassCommandPalette",
    "summary": "A fuzzy, search overlay: type a few letters, get the command you meant, press Enter.",
    "params": [
      {
        "name": "commands",
        "type": "List<Command>",
        "default": "emptyList()"
      },
      {
        "name": "prompt",
        "type": "String",
        "default": "\"Type a command…\"",
        "doc": "Placeholder shown in the empty query field."
      }
    ],
    "examples": [
      "BrassCommandPalette(commands).show(screenRoot)"
    ],
    "signature": "class BrassCommandPalette(\n    commands: List<Command> = emptyList(),\n    private val prompt: String = \"Type a command…\",\n) : BrassWidget(BrassAccent.DEFAULT), BrassDismissable, BrassLayers.Layer, BrassKeyLayer"
  },
  {
    "name": "BrassContextMenu",
    "kind": "class",
    "category": "Surfaces",
    "categoryDir": "surface",
    "slug": "BrassContextMenu",
    "summary": "A small floating panel of action rows shown at a point (typically on right, click).",
    "params": [
      {
        "name": "items",
        "type": "List<Item>"
      },
      {
        "name": "rowWidth",
        "type": "Int"
      }
    ],
    "examples": [],
    "signature": "class BrassContextMenu private constructor(\n    private val items: List<Item>,\n    private val content: UIComponent?,\n    private val rowWidth: Int,\n    private val contentHeight: Int,\n) : UIContainer(), BrassDismissable"
  },
  {
    "name": "BrassEmptyState",
    "kind": "class",
    "category": "Surfaces",
    "categoryDir": "surface",
    "slug": "BrassEmptyState",
    "summary": "What a list shows when it has nothing to show: an icon, a line of explanation, and optionally the one action that would fix it.",
    "params": [
      {
        "name": "icon",
        "type": "BrassIcons.Icon",
        "default": "BrassIcons.NONE"
      },
      {
        "name": "title",
        "type": "String",
        "default": "\"Nothing here\""
      }
    ],
    "examples": [
      "BrassEmptyState(BrassIcons.SEARCH, \"No results\", \"Try a shorter search term\")\n    .withAction(\"Clear filters\") { filters.clear() }",
      "BrassEmptyState(BrassIcons.SEARCH, \"No results\", \"Try a different search term\")"
    ],
    "signature": "class BrassEmptyState(\n    var icon: BrassIcons.Icon = BrassIcons.NONE,\n    var title: String = \"Nothing here\",\n    var detail: String? = null,\n) : BrassWidget(BrassAccent.DEFAULT)",
    "demoName": "empty-state"
  },
  {
    "name": "BrassFrameBase",
    "kind": "class",
    "category": "Surfaces",
    "categoryDir": "surface",
    "slug": "BrassFrameBase",
    "summary": "Everything a window, like frame does, in one place: chrome, drag, collapse, maximize, resize and the open/close animation.",
    "params": [
      {
        "name": "minW",
        "type": "Float",
        "doc": "Smallest the frame may be dragged or squeezed down to."
      },
      {
        "name": "minH",
        "type": "Float"
      },
      {
        "name": "resizable",
        "type": "Boolean",
        "default": "true",
        "doc": "Lay resize grips over the border."
      },
      {
        "name": "collapsible",
        "type": "Boolean",
        "default": "true",
        "doc": "Allow the frame to be rolled up to its title bar."
      },
      {
        "name": "contentPad",
        "type": "Float",
        "default": "0f",
        "doc": "Inset of content from the frame's edges."
      }
    ],
    "examples": [],
    "signature": "class BrassFrameBase(\n    protected val titleBarH: Int,\n    protected val minW: Float,\n    protected val minH: Float,\n    private val resizable: Boolean = true,\n    protected val collapsible: Boolean = true,\n    private val contentPad: Float = 0f,\n) : UIComponent(), BrassFrame"
  },
  {
    "name": "BrassLayers",
    "kind": "object",
    "category": "Surfaces",
    "categoryDir": "surface",
    "slug": "BrassLayers",
    "summary": "Who sits above whom among a screen's floating layers.",
    "params": [],
    "examples": [],
    "signature": "object BrassLayers"
  },
  {
    "name": "BrassLoading",
    "kind": "class",
    "category": "Surfaces",
    "categoryDir": "surface",
    "slug": "BrassLoading",
    "summary": "An **indeterminate** loading bar: a brass block that sweeps back and forth inside a recessed track, easing at each end.",
    "params": [
      {
        "name": "blockFraction",
        "type": "Float",
        "default": "0.32f",
        "doc": "Fraction of the track the moving block occupies."
      },
      {
        "name": "period",
        "type": "Float",
        "default": "1.6f",
        "doc": "Seconds for one full there, and, back sweep."
      }
    ],
    "examples": [
      "BrassLoading()"
    ],
    "signature": "class BrassLoading(\n    private val blockFraction: Float = 0.32f,\n    private val period: Float = 1.6f,\n) : BrassWidget(BrassAccent.DEFAULT)",
    "demoName": "loading"
  },
  {
    "name": "BrassModal",
    "kind": "class",
    "category": "Surfaces",
    "categoryDir": "surface",
    "slug": "BrassModal",
    "summary": "A **dialog**: a titled modal with a bleed, safe body and, optionally, a footer of buttons, the shape every \"ask the user one thing\" popup is, without the boilerplate each one otherwise repeats.",
    "params": [
      {
        "name": "title",
        "type": "String"
      },
      {
        "name": "width",
        "type": "Float"
      },
      {
        "name": "height",
        "type": "Float"
      },
      {
        "name": "showClose",
        "type": "Boolean",
        "default": "true",
        "doc": "Show the close key in the title bar."
      },
      {
        "name": "dismissOnEscape",
        "type": "Boolean",
        "default": "true",
        "doc": "Whether Escape dismisses the dialog."
      },
      {
        "name": "onClose",
        "type": "() -> Unit",
        "default": "{}"
      }
    ],
    "examples": [
      "BrassModal(\"Nickname\", width = 220f, height = 120f)\n    .body { host ->\n        BrassLabel(\"What everyone sees you as.\").constrain { … } childOf host\n        field.constrain { … } childOf host\n    }\n    .footer(\n        BrassButton(\"Clear\", BrassAccent.DANGER) { … },\n        BrassButton(\"Set\", BrassAccent.NICE) { … },\n    )\n    .show(root)"
    ],
    "signature": "class BrassModal @JvmOverloads constructor(\n    title: String,\n    private val width: Float,\n    private val height: Float,\n    showClose: Boolean = true,\n    dismissOnEscape: Boolean = true,\n    onClose: (), > Unit = {},\n)"
  },
  {
    "name": "BrassPanel",
    "kind": "class",
    "category": "Surfaces",
    "categoryDir": "surface",
    "slug": "BrassPanel",
    "summary": "A titled **card** with a padded, self, contained content area, the shape a screen is built out of.",
    "params": [
      {
        "name": "title",
        "type": "String?",
        "default": "null"
      },
      {
        "name": "pad",
        "type": "Float",
        "default": "BrassSpacing.PAD",
        "doc": "Inset of content from the card's edge."
      },
      {
        "name": "gap",
        "type": "Float",
        "default": "BrassSpacing.GAP",
        "doc": "Gap between stacked rows added through add ."
      },
      {
        "name": "hug",
        "type": "Boolean",
        "default": "false",
        "doc": "Measure the panel's own height from its content rather than filling the height it is given."
      }
    ],
    "examples": [
      "BrassPanel(\"SERVER\").add(\n    BrassTextInput(\"\", \"address\"),\n    BrassButton(\"Connect\", BrassAccent.BRASS),\n) childOf parent",
      "panel.row(18f, BrassButton(\"Edit\"), BrassButton(\"Copy\"), BrassButton(\"Delete\"))"
    ],
    "signature": "class BrassPanel @JvmOverloads constructor(\n    private val title: String? = null,\n    private val pad: Float = BrassSpacing.PAD,\n    private val gap: Float = BrassSpacing.GAP,\n    private val filled: Boolean = true,\n    private val layout: Layout = Layout.COLUMN,\n    private val hug: Boolean = false,\n) : BrassContainer()",
    "demoName": "panel"
  },
  {
    "name": "BrassPlotHover",
    "kind": "object",
    "category": "Surfaces",
    "categoryDir": "surface",
    "slug": "BrassPlotHover",
    "summary": "Which slice of a plot the cursor is over.",
    "params": [],
    "examples": [],
    "signature": "object BrassPlotHover"
  },
  {
    "name": "BrassPopup",
    "kind": "class",
    "category": "Surfaces",
    "categoryDir": "surface",
    "slug": "BrassPopup",
    "summary": "A floating, **draggable** sub, window with a title bar and a scrolling form body.",
    "params": [
      {
        "name": "title",
        "type": "String"
      },
      {
        "name": "onClose",
        "type": "() -> Unit",
        "default": "{}"
      },
      {
        "name": "showHeader",
        "type": "Boolean",
        "default": "!modal",
        "doc": "Show the title bar."
      },
      {
        "name": "showCloseButton",
        "type": "Boolean",
        "default": "!modal",
        "doc": "Show the close button in the title bar."
      },
      {
        "name": "resizable",
        "type": "Boolean",
        "default": "!modal",
        "doc": "Allow dragging the edges to resize."
      },
      {
        "name": "collapsible",
        "type": "Boolean",
        "default": "!modal",
        "doc": "Allow double, clicking / minimising the title bar to roll the popup up."
      },
      {
        "name": "dismissOnEscape",
        "type": "Boolean",
        "default": "true",
        "doc": "Whether Escape closes this popup."
      }
    ],
    "examples": [],
    "signature": "class BrassPopup(\n    private val title: String,\n    private val onClose: (), > Unit = {},\n    val modal: Boolean = false,\n    private val showHeader: Boolean = !modal,\n    private val showCloseButton: Boolean = !modal,\n    resizable: Boolean = !modal,\n    collapsible: Boolean = !modal,\n    val dismissOnEscape: Boolean = true,\n    private val scrollingBody: Boolean = true,\n) : BrassFrameBase(\n    titleBarH = if (showHeader) 20 else 0,\n    minW = MIN_W,\n    minH = MIN_H,\n    resizable = resizable,\n    collapsible = collapsible,\n    contentPad = PAD,\n), BrassDismissable"
  },
  {
    "name": "BrassProgressBar",
    "kind": "class",
    "category": "Surfaces",
    "categoryDir": "surface",
    "slug": "BrassProgressBar",
    "summary": "A **determinate** progress bar: a recessed track with a brass fill, an optional caption on the left and a percentage on the right.",
    "params": [
      {
        "name": "showPercent",
        "type": "Boolean",
        "default": "true",
        "doc": "Show the percentage on the right."
      }
    ],
    "examples": [
      "SelfDriving(BrassProgressBar(\"Downloading\"))"
    ],
    "signature": "class BrassProgressBar(\n    var label: String = \"\",\n    private val showPercent: Boolean = true,\n) : BrassWidget(BrassAccent.DEFAULT)",
    "demoName": "progress-bar"
  },
  {
    "name": "BrassTable",
    "kind": "class",
    "category": "Surfaces",
    "categoryDir": "surface",
    "slug": "BrassTable",
    "summary": "A scrollable, selectable table of T, player lists, log views, file browsers, anything row, shaped.",
    "params": [
      {
        "name": "columns",
        "type": "List<Column<T>>"
      },
      {
        "name": "rows",
        "type": "List<T>",
        "default": "emptyList()"
      },
      {
        "name": "rowHeight",
        "type": "Float",
        "default": "16f"
      },
      {
        "name": "onSelect",
        "type": "((T, Int) -> Unit)?",
        "default": "null"
      }
    ],
    "examples": [
      "val table = BrassTable(listOf(\n    BrassTable.Column(\"Player\", 2f) { it.name },\n    BrassTable.Column(\"Ping\", 1f) { \"${it.ping} ms\" },\n), players) { player, _ -> open(player) }"
    ],
    "signature": "class BrassTable<T>(\n    private val columns: List<Column<T>>,\n    rows: List<T> = emptyList(),\n    rowHeight: Float = 16f,\n    onSelect: ((T, Int), > Unit)? = null,\n) : BrassVirtualList<T>(rowHeight, onSelect)",
    "demoName": "table"
  },
  {
    "name": "BrassToast",
    "kind": "class",
    "category": "Surfaces",
    "categoryDir": "surface",
    "slug": "BrassToast",
    "summary": "A notification toast, a keycap chip that **slides in** from the right edge, holds, then slides back out.",
    "params": [
      {
        "name": "message",
        "type": "String"
      },
      {
        "name": "type",
        "type": "Type"
      },
      {
        "name": "sticky",
        "type": "Boolean",
        "doc": "Never expire on its own; closes via the button or close ."
      }
    ],
    "examples": [],
    "signature": "class BrassToast private constructor(\n    private val message: String,\n    private val type: Type,\n    private val sticky: Boolean,\n) : BrassWidget(type.accent), BrassLayers.Layer"
  },
  {
    "name": "BrassTooltip",
    "kind": "object",
    "category": "Surfaces",
    "categoryDir": "surface",
    "slug": "BrassTooltip",
    "summary": "Hover tooltips, drawn as a card above everything else.",
    "params": [],
    "examples": [
      "BrassTooltip.attach(button, \"Start the server\")\nBrassTooltip.attach(icon, \"Danger\", \"This cannot be undone\", accent = BrassAccent.DANGER)"
    ],
    "signature": "object BrassTooltip"
  },
  {
    "name": "BrassTreeView",
    "kind": "class",
    "category": "Surfaces",
    "categoryDir": "surface",
    "slug": "BrassTreeView",
    "summary": "A tree of T, a file browser, a config hierarchy, a nested data structure.",
    "params": [
      {
        "name": "roots",
        "type": "List<T>",
        "default": "emptyList()"
      },
      {
        "name": "label",
        "type": "(T) -> String",
        "doc": "The text for a node."
      },
      {
        "name": "icon",
        "type": "((T) -> BrassIcons.Icon?)?",
        "default": "null",
        "doc": "An optional icon drawn before the label."
      },
      {
        "name": "rowHeight",
        "type": "Float",
        "default": "BrassFont.LINE + 6f"
      },
      {
        "name": "onSelect",
        "type": "((T"
      }
    ],
    "examples": [
      "val tree = BrassTreeView<File>(\n    roots = listOf(project),\n    childrenOf = { it.listFiles()?.toList() ?: emptyList() },\n    label = { it.name },\n)",
      "val tree = BrassTreeView(\n    roots = listOf(DEMO_TREE),\n    childrenOf = { it.children },\n    label = { it.name },\n)\n// Roots start closed so the expansion has somewhere to go; a demo that opens already\n// expanded has nothing left to demonstrate.\ntree"
    ],
    "signature": "class BrassTreeView<T>(\n    roots: List<T> = emptyList(),\n    private val childrenOf: (T), > List<T>,\n    private val label: (T), > String,\n    private val tag: ((T), > Pair<String, BrassTagStyle>?)? = null,\n    private val icon: ((T), > BrassIcons.Icon?)? = null,\n    rowHeight: Float = BrassFont.LINE + 6f,\n    onSelect: ((T, Int), > Unit)? = null,\n) : BrassVirtualList<BrassTreeView.Node<T>>(rowHeight, wrap(onSelect))",
    "demoName": "tree-view"
  },
  {
    "name": "BrassWindow",
    "kind": "class",
    "category": "Surfaces",
    "categoryDir": "surface",
    "slug": "BrassWindow",
    "summary": "The window chrome: a flat panel (fill + inner border + near, black outer ring) with a **title bar**, title, subtitle, and three **working** square control keys on the right (minimise rolls the wind…",
    "params": [
      {
        "name": "title",
        "type": "String"
      },
      {
        "name": "subtitle",
        "type": "String?",
        "default": "null"
      },
      {
        "name": "onClose",
        "type": "() -> Unit",
        "default": "{}"
      },
      {
        "name": "titleBarH",
        "type": "Int",
        "default": "20",
        "doc": "Title bar height."
      },
      {
        "name": "minW",
        "type": "Float",
        "default": "260f",
        "doc": "Minimum size the window can be dragged down to."
      },
      {
        "name": "minH",
        "type": "Float",
        "default": "160f"
      }
    ],
    "examples": [],
    "signature": "class BrassWindow(\n    title: String,\n    subtitle: String? = null,\n    private val onClose: (), > Unit = {},\n    titleBarH: Int = 20,\n    private val controls: Boolean = true,\n    minW: Float = 260f,\n    minH: Float = 160f,\n) : BrassFrameBase(titleBarH, minW, minH)"
  },
  {
    "name": "BrassCodeView",
    "kind": "class",
    "category": "Text",
    "categoryDir": "text",
    "slug": "BrassCodeView",
    "summary": "Read, only syntax, highlighted code with a line, number gutter, a log, a config file, a stack trace, a snippet in a docs panel.",
    "params": [
      {
        "name": "code",
        "type": "String",
        "default": "\"\""
      },
      {
        "name": "gutter",
        "type": "Boolean",
        "default": "true",
        "doc": "Show the line, number gutter."
      }
    ],
    "examples": [
      "BrassCodeView(source, language = \"kotlin\").constrain { width = 100.percent(); height = 200.pixels() }",
      "val view = BrassCodeView(SAMPLE, language = \"kotlin\")\nview.markers = setOf(2)\nview"
    ],
    "signature": "class BrassCodeView(\n    code: String = \"\",\n    language: String? = null,\n    var gutter: Boolean = true,\n) : BrassVirtualList<BrassCodeView.Line>(BrassFont.LINE + 2f)",
    "demoName": "code-view"
  },
  {
    "name": "BrassCopyChip",
    "kind": "object",
    "category": "Text",
    "categoryDir": "text",
    "slug": "BrassCopyChip",
    "summary": "The small copy, to, clipboard chip that sits in the corner of a code surface, the code view, and each fenced block in a markdown document.",
    "params": [],
    "examples": [],
    "signature": "object BrassCopyChip"
  },
  {
    "name": "BrassFont",
    "kind": "object",
    "category": "Text",
    "categoryDir": "text",
    "slug": "BrassFont",
    "summary": "Immediate, mode text drawing for the Re* widgets — a thin shim over Elementa's UIComponent font provider so a widget can paint (and animate the colour of) its own label inside drawContent and have…",
    "params": [],
    "examples": [],
    "signature": "object BrassFont"
  },
  {
    "name": "BrassFuzzy",
    "kind": "object",
    "category": "Text",
    "categoryDir": "text",
    "slug": "BrassFuzzy",
    "summary": "Subsequence matching with a score, \"does this candidate contain the query's letters in order, and how well\".",
    "params": [],
    "examples": [],
    "signature": "object BrassFuzzy"
  },
  {
    "name": "BrassLabel",
    "kind": "class",
    "category": "Text",
    "categoryDir": "text",
    "slug": "BrassLabel",
    "summary": "A line of text that animates in like every other widget.",
    "params": [
      {
        "name": "text",
        "type": "String"
      },
      {
        "name": "shadow",
        "type": "Boolean",
        "default": "true"
      }
    ],
    "examples": [
      "BrassLabel(\"Label text\")"
    ],
    "signature": "class BrassLabel(\n    text: String,\n    tint: Color = Colors.UI_TEXT,\n    var shadow: Boolean = true,\n    var scale: Float = 1f,\n) : BrassWidget(BrassAccent.DEFAULT)",
    "demoName": "label"
  },
  {
    "name": "BrassMarkdown",
    "kind": "class",
    "category": "Text",
    "categoryDir": "text",
    "slug": "BrassMarkdown",
    "summary": "Renders a practical subset of Markdown in the toolkit's palette, for changelogs, help panels, MOTDs and anything else where the text is authored rather than hardcoded into a layout.",
    "params": [
      {
        "name": "markdown",
        "type": "String",
        "default": "\"\""
      },
      {
        "name": "onLink",
        "type": "((String) -> Unit)?",
        "default": "null"
      }
    ],
    "examples": [
      "BrassMarkdown(SAMPLE)"
    ],
    "signature": "class BrassMarkdown(\n    markdown: String = \"\",\n    private val onLink: ((String), > Unit)? = null,\n) : UIComponent()",
    "demoName": "markdown"
  },
  {
    "name": "BrassRelativeTime",
    "kind": "object",
    "category": "Text",
    "categoryDir": "text",
    "slug": "BrassRelativeTime",
    "summary": "\"How long ago\", in words, the arithmetic behind BrassTimeAgo.",
    "params": [],
    "examples": [],
    "signature": "object BrassRelativeTime"
  },
  {
    "name": "BrassSmallCaps",
    "kind": "object",
    "category": "Text",
    "categoryDir": "text",
    "slug": "BrassSmallCaps",
    "summary": "The **small glyph sheets** BrassTag draws its text from, one cell per character, with a JSON atlas beside each sheet giving the cell size and every glyph's advance width:",
    "params": [],
    "examples": [],
    "signature": "object BrassSmallCaps"
  },
  {
    "name": "BrassSyntax",
    "kind": "object",
    "category": "Text",
    "categoryDir": "text",
    "slug": "BrassSyntax",
    "summary": "Syntax highlighting for fenced code blocks, driven by `assets/brassui/syntax_rules.json`, 214 languages under 396 aliases, each a single regex with five named groups (`comment`, `string`, `keyword`…",
    "params": [],
    "examples": [],
    "signature": "object BrassSyntax"
  },
  {
    "name": "BrassTag",
    "kind": "class",
    "category": "Text",
    "categoryDir": "text",
    "slug": "BrassTag",
    "summary": "A **tag / chip**: a short run of text in a flat outlined rectangle, the top edge of a BrassCard and nothing else.",
    "params": [
      {
        "name": "text",
        "type": "String"
      },
      {
        "name": "tint",
        "type": "Color",
        "default": "BRASS"
      }
    ],
    "examples": [
      " 1 px  outline\n 1 px  padding\n 5 px  small-capital ink   <- [INK_H]\n 1 px  padding\n 1 px  outline\n------\n 9 px  = BrassFont.LINE"
    ],
    "signature": "class BrassTag(\n    text: String,\n    tint: Color = BRASS,\n) : BrassWidget(BrassAccent.DEFAULT)",
    "demoName": "tag"
  },
  {
    "name": "BrassTagStyle",
    "kind": "class",
    "category": "Text",
    "categoryDir": "text",
    "slug": "BrassTagStyle",
    "summary": "What a BrassTag *means*, rather than what colour it is.",
    "params": [
      {
        "name": "of",
        "type": "() -> Color"
      }
    ],
    "examples": [],
    "signature": "class BrassTagStyle(private val of: (), > Color)"
  },
  {
    "name": "BrassTextArea",
    "kind": "class",
    "category": "Text",
    "categoryDir": "text",
    "slug": "BrassTextArea",
    "summary": "A **multi, line** text field: word, wrapped, scrollable, selectable, with a caret you can move by clicking, dragging or with the arrow keys.",
    "params": [
      {
        "name": "initial",
        "type": "String",
        "default": "\"\""
      },
      {
        "name": "placeholder",
        "type": "String",
        "default": "\"\""
      },
      {
        "name": "onChange",
        "type": "(String) -> Unit",
        "default": "{}"
      }
    ],
    "examples": [
      "BrassTextArea(placeholder = \"Description\")"
    ],
    "signature": "class BrassTextArea(\n    initial: String = \"\",\n    private val placeholder: String = \"\",\n    val language: String? = null,\n    private val onChange: (String), > Unit = {},\n) : BrassWidget(BrassAccent.DEFAULT), BrassValue<String>, BrassFocusable, BrassTextField",
    "demoName": "text-area"
  },
  {
    "name": "BrassTextEdit",
    "kind": "class",
    "category": "Text",
    "categoryDir": "text",
    "slug": "BrassTextEdit",
    "summary": "Anything that is a text field for the purposes of \"is the user typing right now\".",
    "params": [
      {
        "name": "read",
        "type": "() -> String",
        "doc": "The field's current contents."
      },
      {
        "name": "write",
        "type": "(String) -> Unit",
        "doc": "Replace the contents."
      }
    ],
    "examples": [],
    "signature": "class BrassTextEdit(\n    private val multiline: Boolean,\n    private val read: (), > String,\n    private val write: (String), > Unit,\n    private val onTouch: (), > Unit = {},\n)"
  },
  {
    "name": "BrassTextInput",
    "kind": "class",
    "category": "Text",
    "categoryDir": "text",
    "slug": "BrassTextInput",
    "summary": "A text field with the editing behaviour people expect from a real one: click or drag to select, double, click to select a word, shift+arrows to extend a selection, word, and line, wise motion with…",
    "params": [
      {
        "name": "initial",
        "type": "String",
        "default": "\"\""
      },
      {
        "name": "placeholder",
        "type": "String",
        "default": "\"\""
      },
      {
        "name": "onChange",
        "type": "(String) -> Unit",
        "default": "{}"
      }
    ],
    "examples": [
      "BrassTextInput(placeholder = \"Server name\")"
    ],
    "signature": "class BrassTextInput(\n    initial: String = \"\",\n    private val placeholder: String = \"\",\n    private val onChange: (String), > Unit = {},\n) : BrassWidget(BrassAccent.DEFAULT), BrassValue<String>, BrassFocusable, BrassTextField",
    "demoName": "text-input"
  },
  {
    "name": "BrassTimeAgo",
    "kind": "class",
    "category": "Text",
    "categoryDir": "text",
    "slug": "BrassTimeAgo",
    "summary": "A timestamp that reads as \"how long ago\" and keeps itself current, `just now`, `4m ago`, `3d ago`.",
    "params": [
      {
        "name": "suffix",
        "type": "Boolean",
        "default": "true",
        "doc": "Append \"ago\"."
      },
      {
        "name": "tint",
        "type": "Color",
        "default": "Colors.UI_TEXT_DARK"
      },
      {
        "name": "absolute",
        "type": "((Long) -> String)?",
        "default": "null",
        "doc": "Absolute form shown on hover."
      }
    ],
    "examples": [
      "BrassTimeAgo(lastSeen)                     // \"12m ago\"\nBrassTimeAgo(listedAt, suffix = false)     // \"12m\"",
      "BrassTimeAgo(System.currentTimeMillis() - 5 * 60_000L)"
    ],
    "signature": "class BrassTimeAgo(\n    var timestamp: Long = System.currentTimeMillis(),\n    var suffix: Boolean = true,\n    var tint: Color = Colors.UI_TEXT_DARK,\n    var absolute: ((Long), > String)? = null,\n) : BrassWidget(BrassAccent.DEFAULT)",
    "demoName": "time-ago"
  },
  {
    "name": "BrassWrappedLabel",
    "kind": "class",
    "category": "Text",
    "categoryDir": "text",
    "slug": "BrassWrappedLabel",
    "summary": "The wrapping counterpart to BrassLabel, body text that **word, wraps** to the width it is given and grows taller as it wraps, drawn entirely through BrassFont so it is a real BrassWidget (it shows…",
    "params": [
      {
        "name": "text",
        "type": "String"
      },
      {
        "name": "tint",
        "type": "Color",
        "default": "Colors.UI_TEXT",
        "doc": "Colour at rest; the entrance fade multiplies it."
      },
      {
        "name": "shadow",
        "type": "Boolean",
        "default": "true"
      }
    ],
    "examples": [
      "BrassWrappedLabel(\n    \"A longer run of text that wraps to the width it is given, rather than \" +\n        \"running off the edge of whatever container it was put in.\",\n)"
    ],
    "signature": "class BrassWrappedLabel(\n    text: String,\n    var tint: Color = Colors.UI_TEXT,\n    var shadow: Boolean = true,\n) : BrassWidget(BrassAccent.DEFAULT)",
    "demoName": "wrapped-label"
  }
];
