// Pulls the widget catalog out of the brassui Kotlin sources. For every Brass* type we grab: a short
// one-line blurb (not the whole essay), the constructor parameters with their types/defaults/notes,
// any usage snippets from KDoc ``` fences, and the widget's own demo() builder body when it has one -
// which is the best "here's how you actually make one" example there is. Emits a self-contained
// src/data/widgets.ts so the wiki needs nothing from the Kotlin repo at build time.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, basename, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// Paths are resolved relative to this script, so the wiki can live anywhere inside the repo. The script
// sits at <repo>/wiki/scripts, so core is two levels up, and the output is one level up in src/data.
const HERE = dirname(fileURLToPath(import.meta.url));
const CORE = resolve(HERE, "../../core/src/main/kotlin/net/swzo/brass/ui/kit");
const OUT = resolve(HERE, "../src/data/widgets.ts");

// The one place the wiki learns the current versions: the build's own gradle.properties. Emitting these
// into meta.ts means the Getting Started page's Gradle snippet is generated from the real build, so a
// version bump (brassui's own, or the elementa_version this toolkit tracks) reaches the docs the next
// time the site is generated — which CI does on every deploy. Owner/repo live here too, in one place.
const GRADLE_PROPS = resolve(HERE, "../../gradle.properties");
const META_OUT = resolve(HERE, "../src/data/meta.ts");
const OWNER = "Brassworks-smp";
const REPO = "BrassUi";

function gradleProp(text, key) {
  const m = text.match(new RegExp(`^${key}=(.+)$`, "m"));
  return m ? m[1].trim() : "";
}

function writeMeta() {
  const props = readFileSync(GRADLE_PROPS, "utf8");
  const meta = {
    version: gradleProp(props, "version"),
    elementaVersion: gradleProp(props, "elementa_version"),
    universalcraftVersion: gradleProp(props, "universalcraft_version"),
    owner: OWNER,
    repo: REPO,
    repoUrl: `https://github.com/${OWNER}/${REPO}`,
    packagesUrl: "https://maven.opnsoc.org/releases",
  };
  writeFileSync(
    META_OUT,
    `// GENERATED by scripts/gen-widgets.mjs — do not edit by hand.\n` +
      `// Source: the build's gradle.properties. Re-run \`node scripts/gen-widgets.mjs\` to refresh.\n\n` +
      `export const META = ${JSON.stringify(meta, null, 2)} as const;\n`,
  );
  console.log(`Wrote meta: brassui ${meta.version}, elementa ${meta.elementaVersion}.`);
}
const CATEGORIES = [
  { dir: "input", label: "Inputs", blurb: "Buttons, toggles, sliders, fields. The controls a player drives." },
  { dir: "layout", label: "Layout", blurb: "Panels, scroll areas, flow, spacing. How a screen is arranged." },
  { dir: "surface", label: "Surfaces", blurb: "Cards, dialogs, tables, charts. The framed regions content sits in." },
  { dir: "text", label: "Text", blurb: "Labels, markdown, tags, code. Everything typographic." },
  { dir: "media", label: "Media", blurb: "Images, icons, player heads, item and entity previews." },
];

// --- KDoc cleanup -------------------------------------------------------------------------------

/** Strip the comment framing off a raw `/** ... *\/` block, leaving the marked-down body. */
const kdocBody = (raw) =>
  raw
    .replace(/^\s*\/\*\*/, "")
    .replace(/\*\/\s*$/, "")
    .split("\n")
    .map((l) => l.replace(/^\s*\*\s?/, ""))
    .join("\n");

/** Pull out ``` fenced blocks; returns { text: withoutFences, fences: [code, ...] }. */
function splitFences(body) {
  const fences = [];
  const text = body.replace(/```[a-zA-Z]*\n?([\s\S]*?)```/g, (_, code) => {
    fences.push(code.replace(/\s+$/, ""));
    return "";
  });
  return { text, fences };
}

/** Turn KDoc prose into plain, single-spaced text (drop tags, links, html). */
const proseOf = (text) =>
  text
    .replace(/<\/?p>/g, "\n\n")
    .replace(/<\/?h\d>/g, "\n\n")
    .replace(/^#{1,6}\s+.*$/gm, "") // drop KDoc `### Why ...` section headers - internal rationale
    .replace(/<\/?[a-z][^>]*>/gi, "")
    .replace(/\{@link\s+([^}]+)\}/g, (_, r) => r.split(/[.#]/).pop().trim())
    .replace(/\[([^\]]+)\]\[[^\]]+\]/g, "$1")
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    .replace(/\[([^\]]+)\]/g, (_, r) => r.split(/[.#]/).pop().trim())
    .replace(/\s*-\s*/g, ", ") // the wiki carries no em dashes; fold them into a clause break
    .replace(/[ \t]+/g, " ")
    .replace(/\n{3,}/g, "\n\n")
    .trim();

/** First sentence (or first line) of the prose - the blurb we actually show. */
function firstSentence(prose) {
  const flat = prose.split(/\n\n/)[0].replace(/\s+/g, " ").trim();
  // Split on the first sentence end that isn't an abbreviation like "e.g." - good enough here.
  const m = flat.match(/^(.*?[.!?])(\s|$)/);
  let s = (m ? m[1] : flat).trim();
  if (s.length > 200) s = s.slice(0, 197).trimEnd() + "…";
  return s;
}

// --- constructor parameter parsing --------------------------------------------------------------

/**
 * Depth at each character, respecting () [] {} and generic <...>, strings, and - crucially - NOT
 * mistaking the `>` in a `->` arrow (or `>=`) for a closing angle bracket. `<` only opens a generic
 * when it follows a type-ish character, so a stray comparison never unbalances the scan.
 */
function bracketDepths(s) {
  const depth = new Array(s.length).fill(0);
  let round = 0;
  let angle = 0;
  let str = null;
  for (let i = 0; i < s.length; i++) {
    const c = s[i];
    if (str) {
      depth[i] = round + angle;
      if (c === str && s[i - 1] !== "\\") str = null;
      continue;
    }
    if (c === '"' || c === "'") {
      str = c;
      depth[i] = round + angle;
      continue;
    }
    if (c === "(" || c === "[" || c === "{") {
      round++;
      depth[i] = round + angle;
    } else if (c === ")" || c === "]" || c === "}") {
      depth[i] = round + angle;
      round--;
    } else if (c === "<" && /[A-Za-z0-9_>?,\s]/.test(s[i - 1] || "")) {
      angle++;
      depth[i] = round + angle;
    } else if (c === ">" && s[i - 1] !== "-" && s[i + 1] !== "=" && angle > 0) {
      depth[i] = round + angle;
      angle--;
    } else {
      depth[i] = round + angle;
    }
  }
  return depth;
}

/** Split on top-level commas. */
function splitTopLevel(s) {
  const depth = bracketDepths(s);
  const out = [];
  let buf = "";
  for (let i = 0; i < s.length; i++) {
    if (s[i] === "," && depth[i] === 0) {
      out.push(buf);
      buf = "";
    } else buf += s[i];
  }
  if (buf.trim()) out.push(buf);
  return out;
}

// Find the primary-constructor parameter list `( ... )` for `class NAME`, balanced. Per-param doc
// comments are kept (parseParam reads them), but the brackets inside any comment are neutralised so a
// bracketed aside or link in a doc can't swallow the scan.
function constructorParamText(rawSrc, name) {
  // Neutralise brackets inside comments without deleting the comment (parseParam still reads the doc).
  const src = rawSrc.replace(/\/\*[\s\S]*?\*\//g, (c) => c.replace(/[()[\]{}<>]/g, " ")).replace(/\/\/[^\n]*/g, "");
  const start = src.search(new RegExp(`\\bclass\\s+${name}\\b`));
  if (start < 0) return null;
  // Walk from the class name to the first '(' that opens the ctor, but stop if a '{' (class body)
  // or top-level ':' (supertype list, no ctor) comes first. Skip a generic `<...>` right after name.
  let i = start + src.slice(start).match(new RegExp(`\\bclass\\s+${name}`))[0].length;
  // skip generics
  if (src[skipWs(src, i)] === "<") {
    let d = 0;
    i = skipWs(src, i);
    for (; i < src.length; i++) {
      if (src[i] === "<") d++;
      else if (src[i] === ">") {
        d--;
        if (d === 0) {
          i++;
          break;
        }
      }
    }
  }
  for (; i < src.length; i++) {
    const c = src[i];
    if (c === "(") break;
    if (c === "{" || c === ":") return null; // body or supertype before any ctor parens
    if (c === "@") {
      // annotation / `constructor` keyword may sit before '(' - keep scanning
    }
  }
  if (src[i] !== "(") return null;
  let depth = 0;
  let j = i;
  for (; j < src.length; j++) {
    if (src[j] === "(") depth++;
    else if (src[j] === ")") {
      depth--;
      if (depth === 0) break;
    }
  }
  return src.slice(i + 1, j);
}

const skipWs = (s, i) => {
  while (i < s.length && /\s/.test(s[i])) i++;
  return i;
};

/**
 * The full declaration signature: modifiers, keyword, name, generics, the balanced primary
 * constructor, and the supertype list up to the class body. Comments stripped, blank runs collapsed,
 * em dashes gone - reads as a signature, not an essay.
 */
function fullSignature(rawSrc, name) {
  // Scan a comment-free copy so a stray bracket in KDoc prose can't unbalance the paren/brace count.
  const src = rawSrc.replace(/\/\*[\s\S]*?\*\//g, "").replace(/\/\/[^\n]*/g, "");
  const kw = src.search(new RegExp(`\\b(?:class|object|interface)\\s+${name}\\b`));
  if (kw < 0) return null;
  // Walk back over leading modifiers on the declaration.
  let start = kw;
  const before = src.slice(0, kw).replace(/\s+$/, "");
  const modMatch = before.match(/((?:\b(?:public|internal|private|protected|open|abstract|sealed|final|data|enum|annotation|value|inner|inline)\b\s+)+)$/);
  if (modMatch) start = kw - modMatch[1].length;
  // Find the end: balanced ctor `()` if present, then scan to the class body `{` at depth 0.
  let i = kw;
  let end = src.length;
  let round = 0;
  let angle = 0;
  let sawCtor = false;
  let str = null;
  for (; i < src.length; i++) {
    const c = src[i];
    if (str) {
      if (c === str && src[i - 1] !== "\\") str = null;
      continue;
    }
    if (c === '"' || c === "'") {
      str = c;
      continue;
    }
    if (c === "(") {
      round++;
      sawCtor = true;
    } else if (c === ")") round--;
    else if (c === "<" && /[A-Za-z0-9_>?,\s]/.test(src[i - 1] || "")) angle++;
    else if (c === ">" && src[i - 1] !== "-" && angle > 0) angle--;
    else if (c === "{" && round === 0 && angle === 0) {
      // A `{` at top level: either a `{}` default inside the ctor (round>0 handled) or the class body.
      end = i;
      break;
    }
  }
  let sig = src.slice(start, end);
  sig = sig
    .replace(/\/\*\*[\s\S]*?\*\//g, "")
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/\/\/[^\n]*/g, "")
    .replace(/[ \t]+\n/g, "\n")
    .replace(/\n{2,}/g, "\n")
    .replace(/\s*-\s*/g, ", ")
    .trim();
  if (sig.length > 700) sig = sig.slice(0, 700).trimEnd() + "…";
  return sig || null;
  void sawCtor;
}

/** Parse one raw parameter chunk into { name, type, default?, doc? }. */
function parseParam(chunk) {
  let s = chunk;
  let doc;
  // leading /** ... */ note
  const dm = s.match(/^\s*\/\*\*([\s\S]*?)\*\//);
  if (dm) {
    doc = proseOf(kdocBody(`/**${dm[1]}*/`));
    doc = firstSentence(doc);
    s = s.slice(dm[0].length);
  }
  s = s.replace(/\/\/.*$/gm, "").trim();
  // strip leading annotations like @Foo or @Foo(...)
  while (/^@[\w.]+/.test(s)) {
    s = s.replace(/^@[\w.]+(\([^)]*\))?\s*/, "");
  }
  // strip modifiers
  s = s.replace(/^(?:override\s+|private\s+|internal\s+|protected\s+|public\s+|open\s+|final\s+|val\s+|var\s+|vararg\s+|crossinline\s+|noinline\s+)+/g, "");
  const colon = topLevelIndex(s, ":");
  if (colon < 0) return null;
  const name = s.slice(0, colon).trim();
  let rest = s.slice(colon + 1).trim();
  let def;
  const eq = topLevelIndex(rest, "=");
  if (eq >= 0) {
    def = rest.slice(eq + 1).trim();
    rest = rest.slice(0, eq).trim();
  }
  const type = rest.replace(/\s+/g, " ").trim();
  if (!name || !/^[A-Za-z_]\w*$/.test(name)) return null;
  return { name, type, ...(def ? { default: def } : {}), ...(doc ? { doc } : {}) };
}

/** Index of the first top-level occurrence of a single-char token (respecting brackets/strings). */
function topLevelIndex(s, token) {
  const depth = bracketDepths(s);
  for (let i = 0; i < s.length; i++) {
    if (s[i] === token && depth[i] === 0) {
      // don't treat "==", "=>", ">=", "<=", "->" '=' as a default marker
      if (
        token === "=" &&
        (s[i + 1] === "=" || s[i - 1] === "=" || s[i - 1] === "!" || s[i - 1] === "<" || s[i - 1] === ">")
      )
        continue;
      return i;
    }
  }
  return -1;
}

function parseParams(src, name) {
  const text = constructorParamText(src, name);
  if (text == null) return [];
  return splitTopLevel(text)
    .map(parseParam)
    .filter(Boolean);
}

// --- demo extraction ----------------------------------------------------------------------------

/** Extract { demoName, snippet } from a `override fun demo() = BrassDemo("id", ...) { body }`. */
function extractDemo(src) {
  const idx = src.indexOf("BrassDemo(");
  if (idx < 0) return {};
  const nameM = src.slice(idx).match(/BrassDemo\(\s*"([^"]+)"/);
  const demoName = nameM ? nameM[1] : undefined;
  // Grab the trailing lambda body: find the '{' that closes the BrassDemo(...) call args.
  let i = idx + "BrassDemo".length;
  // skip to end of the (...) argument list
  let depth = 0;
  for (; i < src.length; i++) {
    if (src[i] === "(") depth++;
    else if (src[i] === ")") {
      depth--;
      if (depth === 0) {
        i++;
        break;
      }
    }
  }
  i = skipWs(src, i);
  let snippet;
  if (src[i] === "{") {
    let d = 0;
    const start = i;
    for (; i < src.length; i++) {
      if (src[i] === "{") d++;
      else if (src[i] === "}") {
        d--;
        if (d === 0) {
          i++;
          break;
        }
      }
    }
    const body = src.slice(start + 1, i - 1);
    snippet = dedent(body).trim();
    if (snippet.length > 400 || !snippet) snippet = undefined;
  }
  return { demoName, snippet };
}

/** Remove common leading indentation from a block. */
function dedent(s) {
  const lines = s.replace(/^\n+/, "").replace(/\s+$/, "").split("\n");
  const indents = lines.filter((l) => l.trim()).map((l) => l.match(/^\s*/)[0].length);
  const min = indents.length ? Math.min(...indents) : 0;
  return lines.map((l) => l.slice(min)).join("\n");
}

// --- main ---------------------------------------------------------------------------------------

const entries = [];
for (const cat of CATEGORIES) {
  const dir = join(CORE, cat.dir);
  for (const f of readdirSync(dir).filter((x) => x.endsWith(".kt"))) {
    const name = basename(f, ".kt");
    const src = readFileSync(join(dir, f), "utf8");

    const re = new RegExp(
      `(/\\*\\*[\\s\\S]*?\\*/)\\s*(?:@[\\w.]+(?:\\([^)]*\\))?\\s*)*(?:public |internal |open |abstract |sealed |final |data |enum )*(class|object|interface|enum class)\\s+${name}\\b`,
    );
    const m = src.match(re);
    let kind = "class";
    let fences = [];
    let summary = "";
    if (m) {
      kind = m[2].includes("object") ? "object" : m[2].includes("interface") ? "interface" : "class";
      const split = splitFences(kdocBody(m[1]));
      fences = split.fences;
      summary = firstSentence(proseOf(split.text));
    }

    // Declaration signature: class/object keyword up to the opening brace or supertype list.
    let signature = fullSignature(src, name) ?? `${kind} ${name}`;

    const params = kind === "class" ? parseParams(src, name) : [];
    const { demoName, snippet } = extractDemo(src);

    // Usage examples: KDoc fences first (curated), then the demo builder body (real construction).
    const examples = [...fences];
    if (snippet && !examples.some((e) => e.includes(snippet.split("\n")[0].trim()))) {
      examples.push(snippet);
    }

    entries.push({
      name,
      kind,
      category: cat.label,
      categoryDir: cat.dir,
      slug: name,
      summary,
      params,
      examples,
      signature,
      ...(demoName ? { demoName } : {}),
    });
  }
}

entries.sort((a, b) => a.category.localeCompare(b.category) || a.name.localeCompare(b.name));

const out = `// GENERATED by scripts/gen-widgets.mjs - do not edit by hand.
// Source: brassui core Kotlin sources. Re-run \`node scripts/gen-widgets.mjs\` to refresh.

export type Param = {
  name: string;
  type: string;
  default?: string;
  doc?: string;
};

export type Widget = {
  name: string;
  kind: "class" | "object" | "interface";
  category: string;
  categoryDir: string;
  slug: string;
  summary: string;
  params: Param[];
  examples: string[];
  signature: string;
  demoName?: string;
};

export const CATEGORIES = ${JSON.stringify(CATEGORIES.map(({ dir, label, blurb }) => ({ dir, label, blurb })), null, 2)} as const;

export const WIDGETS: Widget[] = ${JSON.stringify(entries, null, 2)};
`;

writeFileSync(OUT, out);
const withEx = entries.filter((e) => e.examples.length).length;
const withParams = entries.filter((e) => e.params.length).length;
console.log(`Wrote ${entries.length} widgets - ${withParams} with params, ${withEx} with examples.`);

writeMeta();
